<a href="https://colab.research.google.com/github/junehyung1112/hello-world/blob/master/2%EA%B0%95_numpy_%EA%B0%95%EC%9D%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#파이썬의 numpy 모듈은 배열간 고속 연산을 가능하게 함.
#python에서 numpy 모듈이 필요한 이유: python은 스크립트언어라 반복문으로 배열 계산시 시간이 많이 필요
#넘파이 모듈을 사용하면 상황에 따라 다르지만 행렬곱의 경우 안쓰는것보다 6배 더 빠름.
#python 수치 연산의 문제점:
#리스트를 이용해 행렬 및 벡터를 생성하고 연산을 수행
#하지만 다양한 행렬과 벡터에 대한 직접 연산을 지원하지 않음
#다차원 데이터를 효과적으로 연산할 수 없고 처리 속도가 매우 느림.
#이를 해결하기 위해 넘파이가 개발
#넘파이는 다차원 고속 배열지원하고 다차원 배열에 대해 직접 연산을 지원함.
#다양한 선형 대수, 행렬 변환 함수를 지원함.
import numpy as np

v = np.array([[1,2],[3,4],[5,6]]) # 3*2 행렬, 3개의 리스트로 구성되어 있고 각각의 리스트가 2개의 원소 지님
m = np.array([[1,2,3]]) #행백터는 벡터로 보기보다는 행렬로 보는게 편함.
m = np.array([[1],[2],[3]]) #3행 1열 -> 열벡터
m = np.array([[1,2,3],[4,5,6]]).reshape(3,2) #reshape를 이용해서 2*3 행렬을 3*2행렬로 변환 가능. 이 때 원소 개수가 일치해야함.
m = np.array([[1,2,3],[4,5,6]]).T #transpose 함수 = 행렬에 대한 전체 연산을 위해 제공.
#numpy는 인덱싱과 슬라이싱을 통해 데이터의 특정 위치의 원소에 접근할 수 있음.
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a[1,1] #,를 이용한 인덱싱으로 특정 위치 값 읽을 수 있음. 
a[0]  # 행렬의 첫번째 행을 의미.
a[:, 1] #행렬의 두번째 열을 의미.
a[1, 1:3] # 두번째 행의 2열~4열을 의미.

#2개 벡터나 행렬에 대해 손쉽게 사칙연산 가능
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])
c = a + b # + 연산자를 사용해서 두 벡터의 합 계산 가능.
#연산 시 두 행렬의 데이터 타입은 큰 쪽으로 맞춰지고 두 행렬의 크기가 다른 경우 오류가 발생.
#matmul 함수를 이용해서 두 매트릭스간 곱셈이 가능
x = np.array([[1,2], [4,5], [6,7]]) #3*2
y = np.array([[1,2],[4,5]]) #2*2
print(np.matmul(x,y)) #3*2

[[ 9 12]
 [24 33]
 [34 47]]


In [0]:

import numpy as np
import numpy.linalg as lin #역행렬 계산을 위해
import time

#numpy 뱁열 객체를 생성
a = np.array(2.0)
print(a)
print(type(a)) #numpy 객체
#()를 사용해서 다차원 배열 shape의 크기를 알 수 있음.

print(a.shape) #실수 한개로 이루어져 있어 0차원

b = np.array([2.0])
print(b) #대괄호로 출력되는 건 데이터가 벡터임을 의미.
print(b.shape)

c = np.array([2,3,4])
print(c)
print(c.shape) #크기가 3인 백터

m = np.array([[1,2],[3,4],[5,6]])
print(m)
print(m.shape)
print("행 :", m.shape[0]) #행의 크기를 의미.
print("열 :", m.shape[1]) #열의 크기를 의미.

m = np.array([[1,2,3]]) #한개의 행으로만 이루어짐 -> 행백테
print(m) 

m = np.array([[1],[2],[3]]) #한개의 열로만 이루어짐 -> 열벡터
print(m)
print(m.shape) #(행의 크기, 열의 크기)

#numpy array는 모든 원소의 타입이 동일하다고 가정함.
#타입이 int32면 모두 정수
#정수와 실수가 섞여있으면 float64로 정의.
#numpy에서는 list객체 타입을 통해 자동으로 형을 결정.
#고속 수치 계산을 위해 단일 데이터 타입을 사용함.

#주의할 사항 파이썬은 2차원 배열 만들 때 리스트를 이용 -> 각 행의 개수가 다를 수 있음
#but numpy는 격자 형태의 array만 지원.
a = [[1,2 ], [3,4,5]]
print(a) #각 행마다 원소개수가 다른 행렬이 만들어짐.
b = np.array([[1,2], [3,4,5]])
print(b) #넘파이는 격자 어레이만 마들어야하기 때문에 두개의 리스트를 원소로 갖는 객체가 만들어짐.


2.0
<class 'numpy.ndarray'>
()
[2.]
(1,)
[2 3 4]
(3,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
행 : 3
열 : 2
[[1 2 3]]
[[1]
 [2]
 [3]]
(3, 1)
[[1, 2], [3, 4, 5]]
[list([1, 2]) list([3, 4, 5])]


In [0]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a[0,0]) # 1행 1열
print(a[0]) # 1행.
print(a[:,1]) #두번째 열의 값
print(a[1, 1:3]) #두번째 행 2~4열까지.

i = [0,2]
b = a[i, :] #b는 0행과 2행의 모든 열 정보 출력
print(b)

c = np.array([1,2,3,4,5,6,7])
print(c[0::2]) #0부터 2씩 증가시켜서 출력

print(a[1:-1]) #두번째 행부터 마지막행(여기선 3행) 전까지

print(a[1:]) #1행부터 마지막행까지

a[1, 2] = 7  #원소 변경 가능
a[:, 0] = [0,9,1] #행 전체 변경 가능


1
[1 2 3]
[2 5 8]
[5 6]
[[1 2 3]
 [7 8 9]]
[1 3 5 7]
[[4 5 6]]
[[4 5 6]
 [7 8 9]]


In [0]:
#파일로 저장 하거나 읽어 오는게 가능
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.save("a.npy", a)
b = np.load("a.npy")
print(b)

#csv 파일은 일반 에디터로 손쉽게 수정 삭제 가능
# numpy는 load text로 손쉽게 csv 파일 사용가능.
data = np.loadtxt("iris.csv", delimiter=",", dtype = np.float32)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


OSError: ignored